// \s([-+*!<>/]?==?=?|\?|[*/+%-]|=>|&&|\|\||<|>|:|,)\s
function conversion(input_id) {
  var colorVal=document.getElementById(input_id).value;
  ['hex','hsv','rgb','rgbArr','cmyk','hsl','hsb','hwb','xyz','lab','lch','hcg'].forEach(n=>document.getElementById(n).textContent=ccolor(colorVal)[n]().get());
  const view=document.querySelector("#view");
  view.innerHTML='加载中';
  view.style.background=ccolor(colorVal).hex().get();
  view.style.color=ccolor(colorVal).hex().get();
}

// ccolor V1.0
// Made by 云杉spruce
// 未经允许，不能将文件用于其他网站，不能修改、衍生代码。
(()=>{"use strict";
function pc(j){let r=j.fn?j.fn[this.type]?j.fn[this.type]:undefined:undefined;if(r==undefined)return this;r=typeof r=='function'?r.call(this,this.val):typeof r=='string'?this[r]()[j.n]():r===1?this:r;return r.val?r.val:r}
const ccolor=(c)=>{return new ccolor.prototype.init(c)},
Hex={hex:1,rgb:function([r,g,b]){return [((1<<24)+(r<<16)+(g<<8)+b).toString(16).slice(1)]},hsv:'rgb',rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
Rgb={hex:function([h]){return h.match(/.{2}/g).map(c=>parseInt(c,16))},rgb:1,hsv:function([h,s,v]){let i,f,p1,p2,p3;s=s<0?0:s>1?1:s;v=v<0?0:v>1?1:v;h%=360;if(h<0)h+=360;h/=60;i=Math.floor(h);f=h-i;p1=v*(1-s);p2=v*(1-s*f);p3=v*(1-s*(1-f));return (i==0?[v,p3,p1]:i==1?[p2,v,p1]:i==2?[p1,v,p3]:i==3?[p1,p2,v]:i==4?[p3,p1,v]:i==5?[v,p1,p2]:[0,0,0]).map(v=>parseFloat(v*255))},rgbArr:function(arr){return arr.map(v=>parseFloat(v*255))},cmyk:function([c,m,y,k]){[c,m,y,k].map(v=>v/=100);return [c,m,y].map(v=>parseFloat((1-Math.min(1,v*(1-k)+k))*255))},hsl:function([h,s,l]){h/=360,s/=100,l/=100;let r,g,b;if(s===0){r=l;g=l;b=l}else{const H=t=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p},q=l<0.5?l*(1+s):l+s-l*s,p=2*l-q;r=H(h+1/3);g=H(h);b=H(h-1/3)}return [r,g,b].map(v=>parseFloat(v*255))},hsb:function([h,s,b]){s/=100;b/=100;const k=(n)=>(n+h/60)%6,f=(n)=>b*(1-s*Math.max(0,Math.min(k(n),4-k(n),1)));return [5,3,1].map(v=>parseFloat(255*f(v)))},hwb:function([H,W,B]){H/=360,W/=100,B/=100;const R=W+B;let i,v,f,n,r,g,b;if(R>1){W/=R;B/=R}i=Math.floor(6*H);v=1-B;f=6*H-i;if((i&0x01)!==0)f=1-f;n=W+f*(v-W);r=i==0||i==5?v:i==1||i==4?n:i==2||i==3?W:0;g=i==0||i==1?n:i==2||i==5?v:i==3||i==4?W:0;b=i==4||i==5?v:i==0||i==3?n:i==1||i==2?W:0;return [r,g,b].map(v=>parseFloat(v*255))},xyz:function([x,y,z]){x/=100,y/=100,z/=100;var rgb=[x*3.2404542+y*-1.5371385+z*-0.4985314,x*-0.9692660+y*1.8760108+z*0.0415560,x*0.0556434+y*-0.2040259+z*1.0572252];rgb=rgb.map(v=>v<0?0:Math.min(1,v>0.0031308?1.055*(Math.pow(v,1/2.4))-0.055:12.92*v));return [0,1,2].map(v=>parseFloat(rgb[v]*255))},lab:'xyz',lch:'xyz',hcg:function([H,C,G]){H=H/360*6;C/=100;G/=100;if(C<=0)return [G*255,G*255,G*255];var i=Math.floor(H),f=H-i,q=C*(1-f),t=C*f,I=i%6,r=[C,q,0,0,t,C][I],g=[t,C,C,q,0,0][I],b=[0,0,t,C,C,q][I];return [r,g,b].map(v=>(v+((1-C)*G))*255)},luv:'xyz',yuv:function([y,u,v]){let r=y+1.403*(v-128),g=y-0.714*(v-128)-0.344*(u-128),b=y+1.773*(u-128);return [r,g,b].map(v=>Math.min(255,Math.max(0,v)))}},
Hsv={hex:'rgb',rgb:function([r,g,b]){r/=255,g/=255,b/=255;var min=Math.min(r,g,b),max=Math.max(r,g,b),d=max-min,v=max,h,s;if(d===0){h=0;s=0}else{s=d/v;var [dr,dg,db]=[r,g,b].map(c=>((v-c)/6+d/2)/d);h=r==v?db-dg:g==v?1/3+dr-db:b==v?2/3+dg-dr:undefined;if(h<0)h+=1;if(h>1)h-=1}return [h*360,s*100,v*100]},hsv:1,rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:function([h,w,b]){w/=100,b/=100;return [h,(1-(w/(1-b)))*100,(1-b)*100]},xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
RgbArr={hex:'rgb',rgb:function(arr){return arr.map(v=>parseFloat(v/255))},hsv:'rgb',rgbArr:1,cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
Cmyk={hex:'rgb',rgb:function([r,g,b]){if(r==0&&g==0&&b==0)return [0,0,0,1];var [c,m,y]=[r,g,b].map(v=>1-(v/255)),min=Math.min(c,Math.min(m,y));c=(c-min)/(1-min);m=(m-min)/(1-min);y=(y-min)/(1-min);return [c,m,y,min].map(v=>v*100)},hsv:'rgb',rgbArr:'rgb',cmyk:1,hsl:'rgb',hsb:'rgb',hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
Hsl={hex:'rgb',rgb:function([r,g,b]){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h,s,l=(max+min)/2;if(max===min)h=s=0;else{s=(l>0.5)?d/(2-max-min):d/(max+min);h=(max==r?(g-b)/d+((g<b)?6:0):max==g?(b-r)/d+2:(r-g)/d+4)/6}return [h*360,s*100,l*100]},hsv:'rgb',rgbArr:'rgb',cmyk:'rgb',hsl:1,hsb:'rgb',hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
Hsb={hex:'rgb',rgb:function([r,g,b]){r/=255,g/=255,b/=255;const max=Math.max(r,g,b),d=max-Math.min(r,g,b),h=d===0?0:d&&max===r?(g-b)/d:max===g?2+(b-r)/d:4+(r-g)/d;return [60*(h<0?h+6:h),max&&(d/max)*100,max*100].map(v=>parseFloat(v))},hsv:'rgb',rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:1,hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
Hwb={hex:'rgb',rgb:'hsv',hsv:function([h,s,v]){s/=100,v/=100;return [h,((1-s)*v)*100,(1-v)*100]},rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:1,xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:'rgb'},
Xyz={hex:'rgb',rgb:function([r,g,b]){r/=255,g/=255,b/=255;const f=v=>(v>0.04045?Math.pow((v+0.055)/1.055,2.4):v/12.92)*100;r=f(r);g=f(g);b=f(b);return [r*0.4124564+g*0.3575761+b*0.1804375,r*0.2126729+g*0.7151522+b*0.0721750,r*0.0193339+g*0.1191920+b*0.9503041]},hsv:'rgb',rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:'rgb',xyz:1,lab:function([l,a,b]){var y=(l+16)/116,x=a/500+y,z=y-b/200,js=v=>{var V=Math.pow(v,3);return V>0.008856?V:(v-16/116)/7.787};return [Math.min(Xyz.x,Xyz.x*js(x)),Math.min(Xyz.y,Xyz.y*js(y)),Math.min(Xyz.y,Xyz.z*js(z))]},lch:'lab',hcg:'rgb',luv:function([l,u,v]){var U,V,uv,x,y,cy;y=(l+16)/116;cy=y*y*y;y=cy>0.008856?cy:(y-16/116)/7.787;uv=(Xyz.x+(15*Xyz.y)+(3*Xyz.z));U=(4*Xyz.x)/uv;V=(9*Xyz.y)/uv;u=u/(13*l)+U;v=v/(13*l)+V;y=y*100;x=-1*(9*y*u)/((u-4)*v-u*v);return [x,y,(9*y-(15*v*y)-(v*x))/(3*v)]},yuv:'rgb',x:95.047,y:100,z:108.883},
Lab={hex:'xyz',rgb:'xyz',hsv:'xyz',rgbArr:'xyz',cmyk:'xyz',hsl:'xyz',hsb:'xyz',hwb:'xyz',xyz:function([x,y,z]){x/=Xyz.x,y/=Xyz.y,z/=Xyz.z;const js=v=>v>0.008856?Math.pow(v,1/3):(7.787*v)+16/116,jy=js(y);return [(116*jy)-16,500*(js(x)-jy),200*(jy-js(z))]},lab:1,lch:function([l,c,h]){var H=Math.PI*h/180;return [l,Math.cos(H)*c,Math.sin(H)*c]},hcg:'xyz',luv:'xyz',yuv:'xyz'},
Lch={hex:'xyz',rgb:'xyz',hsv:'xyz',rgbArr:'xyz',cmyk:'xyz',hsl:'xyz',hsb:'xyz',hwb:'xyz',xyz:'lab',lab:function([l,a,b]){var h=Math.atan2(b,a);return [l,Math.sqrt(a*a+b*b),h>0?180*h/Math.PI:360-(180*Math.abs(h)/Math.PI)]},lch:1,hcg:'xyz',luv:function(luv){return Lab.lch(luv)},yuv:'xyz'},
Hcg={hex:'rgb',rgb:function([r,g,b]){r/=255,g/=255,b/=255;var max=Math.max(r,g,b),min=Math.min(r,g,b),H=0,C=max-min,G=0;if(C<1)G=min/(1-C);if(C>0)H=(max==r?(g-b)/C+(g<b?6:0):max==g?(b-r)/C+2:(r-g)/C+4)/6;return [H*360,C*100,G*100]},hsv:'rgb',rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:1,luv:'rgb',yuv:'rgb'},
Luv={hex:'xyz',rgb:'xyz',hsv:'xyz',rgbArr:'xyz',cmyk:'xyz',hsl:'xyz',hsb:'xyz',hwb:'xyz',xyz:function([x,y,z]){var l,U,V,UV,uv=(x+(15*y)+(3*z)),u=(4*x)/uv,v=(9*y)/uv;y=y/100;y=y>0.008856?Math.pow(y,1/3):7.787*y+16/116;UV=(Xyz.x+(15*Xyz.y)+(3*Xyz.z));U=(4*Xyz.x)/UV;V=(9*Xyz.y)/UV;l=(116*y)-16;return [l,13*l*(u-U),13*l*(v-V)]},lab:'xyz',lch:function(luv){return Lab.lch(luv)},hcg:'xyz',luv:1,yuv:'xyz'},
Yuv={hex:'rgb',rgb:function([r,g,b]){let y=0.299*r+0.587*g+0.114*b;return [y,(b-y)*0.564+128,(r-y)*0.713+128].map(v=>Math.min(255,Math.max(0,v)))},hsv:'rgb',rgbArr:'rgb',cmyk:'rgb',hsl:'rgb',hsb:'rgb',hwb:'rgb',xyz:'rgb',lab:'rgb',lch:'rgb',hcg:'rgb',luv:'rgb',yuv:1},
colorSpace=[{n:'hex',fn:Hex,r:/^(?:#)?([0-9A-F]{3}){1,2}([0-9A-F]{2})?$/i},{n:'rgb',fn:Rgb,r:/^rgba?\(\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?(\s*,\s*(?:1(?:\.0+)?|0(?:\.\d+)?))?\s*\)$/i},{n:'hsv',fn:Hsv,suf:['°','%','%'],r:/^hsva?\(\s*(\d+(\.\d+)?)(?:°|deg)?\s*,\s*(\d+(\.\d+)?)%?\s*,\s*(\d+(\.\d+)?)%?\s*(?:,\s*((0(?:\.\d+)?)|(?:1(?:\.0+)?)))?\s*\)$/i},{n:'rgbArr',fn:RgbArr,r:/^\[\s*(0(\.\d+)?|1(\.0+)?)\s*,\s*(0(\.\d+)?|1(\.0+)?)\s*,\s*(0(\.\d+)?|1(\.0+)?)\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\]$/i},{n:'cmyk',fn:Cmyk,suf:['%','%','%','%'],r:/^cmyka?\(\s*(\d+(\.\d+)?)%?\s*,\s*(\d+(\.\d+)?)%?\s*,\s*(\d+(\.\d+)?)%?\s*,\s*(\d+(\.\d+)?)%?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'hsl',fn:Hsl,suf:['°','%','%'],r:/^hsla?\(\s*(\d+(\.\d+)?(?:°|deg)?)\s*,\s*(\d+(\.\d+)?%?)\s*,\s*(\d+(\.\d+)?%?)\s*(?:,\s*(0(?:\.\d+)?)|(?:1(?:\.0+)?))?\s*\)$/i},{n:'hsb',fn:Hsb,suf:['°','%','%'],r:/^hsba?\(\s*(\d+(\.\d+)?)(?:°|deg)?\s*,\s*\d+(\.\d+)?%?\s*,\s*\d+(\.\d+)?%?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'hwb',fn:Hwb,suf:['°','%','%'],r:/^hwba?\(\s*(-?\d+(\.\d+)?(?:°|deg)?)\s*,\s*(\d+(\.\d+)?%?)\s*,\s*(\d+(\.\d+)?%?)\s*(?:,\s*(0(?:\.\d+)?)|(?:1(?:\.0+)?))?\s*\)$/i},{n:'xyz',fn:Xyz,r:/^xyza?\(\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'lab',fn:Lab,suf:['%'],r:/^laba?\(\s*(-?\d+(\.\d+)?%?\s*,\s*){2}-?\d+(\.\d+)?%?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'lch',fn:Lch,suf:['%','%','°'],r:/^lcha?\(\s*\d+(\.\d+)?%?\s*,\s*\d+(\.\d+)?%?\s*,\s*\d+(\.\d+)?(?:°|deg)?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'hcg',fn:Hcg,suf:['°','%','%'],r:/^hcga?\(\s*-?\d+(\.\d+)?(?:°|deg)?\s*,\s*\d+(\.\d+)?%?\s*,\s*\d+(\.\d+)?%?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'luv',fn:Luv,suf:['%'],r:/^luva?\(\s*\d+(\.\d+)?%?\s*,\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i},{n:'yuv',fn:Yuv,r:/^yuva?\(\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?\s*,\s*\d+(\.\d+)?\s*(?:,\s*(0(\.\d+)?|1(\.0+))\s*)?\)$/i}];

ccolor.prototype={init: function(c=""){if(typeof c!=='string')return this;c=c.trim();const r=colorSpace.find(j=>j.r.test(c));if(r){if(r.n=='hex'){const hex=c.replace("#",'').replace(/^(.)(.)(.)$/,'$1$1$2$2$3$3');this.val=[hex.slice(0,6).toLowerCase()];this.a=(parseInt(hex.slice(6),16)||255)/255}else if(r.n=='rgbArr'){const arr=JSON.parse(c);if(arr.length>=4){this.val=arr.slice(0,arr.length-1);this.a=arr[arr.length-1]}else{this.val=arr;this.a=1}}else{const ai=c.lastIndexOf('('),arr=(c.match(/-?\d+(\.\d+)?/g)||[]).map(parseFloat);if(ai!==-1&&c.charAt(ai-1)=="a"&&arr.length===ai){this.val=arr.slice(0,arr.length-1);this.a=arr[arr.length-1]}else{this.val=arr;this.a=1}}this.str=c;this.type=r.n}return this}};
colorSpace.forEach(j=>{ccolor.prototype[j.n]=function(){let r=pc.call(this,j);const suf=j.suf||[];this.val=r;this.str=j.n==='hex'?'#'+r[0]:j.n=='rgbArr'?`[${r.join(', ')}]`:j.n+'('+r.map((v,i)=>v+(suf[i]||'')).join(', ')+')';this.type=j.n;return this};if(j.n!=='rgbArr')ccolor.prototype[j.n+'a']=function(){let r=pc.call(this,j);const suf=j.suf||[];this.val=r;this.str=j.n==='hex'?'#'+r[0]+Math.round(this.a*255).toString(16).padStart(2,'0'):j.n=='rgbArr'?`[${r.join(', ')}, ${this.a}]`:j.n+'a('+r.map((v,i)=>v+(suf[i]||'')).join(', ')+', '+this.a+')';this.type=j.n;return this}});
ccolor.prototype.get=function(){return this.type==='rgbArr'?this.str.replace(/(-?\d+\.\d+)/g,s=>parseFloat(parseFloat(s).toFixed(3))):this.str.replace(/(-?\d+\.\d+)/g,s=>Math.round(parseFloat(s)))};
ccolor.prototype.init.prototype=ccolor.prototype;
window.ccolor=ccolor;
})()